language: go


env:
  - DEP_VERSION="0.5.0"


go:
  - 1.10.1
  - tip

# Only clone the most recent commit.
git:
  depth: 1

before_script:
  - go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - cd src/aws-key-importer && dep ensure

script:
  - cd src/aws-key-importer && go build -o ../../bin/aws-key-importer
