language: go

go:
  - 1.14.1
  - tip

# Only clone the most recent commit.
git:
  depth: 1

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v${GOLINT_VERSION:-1.10.2}

install:
  - go mod download

script:
  - cd ${TRAVIS_BUILD_DIR}/cmd/aws-key-importer && golangci-lint run || true
  - cd ${TRAVIS_BUILD_DIR}/cmd/aws-key-importer && go build -o ../../out/aws-key-importer
