language: go

go:
  - 1.10.1
  - tip

# Only clone the most recent commit.
git:
  depth: 1

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v${GOLINT_VERSION:-1.10.2}
# Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION:-0.5.0}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - cd src/aws-key-importer && dep ensure

script:
  - cd src/aws-key-importer && golangci-lint run || true
  - cd src/aws-key-importer && go build -o ../../bin/aws-key-importer
